### ISSUE TITLE
ng test failed

### ISSUE THREAD

**Issue by clakech** [alm-chrome-tools/vsts-follower#51]
Hi,

I just install the project locally and get a failure on ng test:

```
22 08 2017 16:33:40.421:ERROR [karma]: TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/Compilation.js:605:9)
    at next (/Users/vsts-follower/vsts-follower-chrome/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/vsts-follower/vsts-follower-chrome/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at next (/Users/vsts-follower/vsts-follower-chrome/node_modules/tapable/lib/Tapable.js:204:14)
    at ExtractTextPlugin.<anonymous> (/Users/vsts-follower/vsts-follower-chrome/node_modules/extract-text-webpack-plugin/index.js:305:5)
```

**Comment by clakech** [comment]
This problem is link to a webpack issue: https://github.com/webpack/webpack/issues/4072

I solve this issue with a `npm install @angular/cdk --save`
